version: '3.7'

services:
  ddb:
    image: amazon/dynamodb-local
    entrypoint: [ java, -jar, DynamoDBLocal.jar, -inMemory, -sharedDb ]
    working_dir: /home/dynamodblocal
    ports:
      - "8000:8000"
