AWSTemplateFormatVersion: "2010-09-09"
Description: Delivery  events to topic
Transform: "AWS::Serverless-2016-10-31"

Parameters:

  PreReqStack:
    Description: >
      Name of Pre Requests stack, which is in same account & region of this stack.  Values are automatically
      extracted from Stack Exports.
    Type: String
    MinLength: 1
    MaxLength: 128
    AllowedPattern: "[a-zA-Z0-9-]+"
    ConstraintDescription: >
      Stack name must start with an alphabetic character and can't be longer
      than 128 characters

Resources:

  PipelineEventCallback:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.7
      CodeUri: lambdas/pipeline_event_callback
      Timeout: 60
      MemorySize: 128
      Environment:
        Variables:
          # "ProjectIdentifier-"
          PIPELINE_PREFIX: !Join [ "", [ { Fn::ImportValue: !Sub "${PreReqStack}:ProjectIdentifier" }, "-" ] ]
          SNS_TOPIC_ARN: { Fn::ImportValue: !Sub "${PreReqStack}:NotificationTopicArn" }
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: { Fn::ImportValue: !Sub "${PreReqStack}:NotificationTopic" }

      Events:
        # All CodePipeline Events
        CodePipelineEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.codepipeline
              detail-type:
                - CodePipeline Pipeline Execution State Change
        # Action Failures
        CodePipelineActionEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.codepipeline
              detail-type:
                - CodePipeline Action Execution State Change
              detail:
                state:
                  - FAILED
                  - CANCELED
