AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Cross account roles to be assumed by CodePipeline service in tools account.

Parameters:

  ToolsAccount:
    Description: >
      AWS AccountNumber for tools (pipelines and artifact infra).
    Type: String

  ArtifactBuckets:
    Description: >
      A list of S3 artifact buckets in Tools Account, first one must in the primary region.
    Type: CommaDelimitedList

  KmsKeyArns:
    Description: >
      A list of KMS CMK ARNs in Tools account, first one must in the primary region.
    Type: CommaDelimitedList

  AdditonalRegions:
    Description: >
      Number of additional secondary regions, must match number of items in ArtifactBuckets and KmsKeyArns.
    Type: Number
    Default: 0
    MinValue: 0
    MaxValue: 1

  ProjectIdentifier:
    Description: >
      An unique identifier for the project, must be identical in all templates deployed using same artifact bucket.
    Type: String
    Default: samwise
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[A-Za-z][A-Za-z0-9]*"
    ConstraintDescription: Only alphanumeric string is allowed.

  PermissionsBoundary:
    Description: >
      ARN of the policy used to set the permissions boundary for the canned CloudFormation deploy role,
      which assumes administrator access.
      Setting this to empty string disables PermissionsBoundary.
    Type: String
    Default: ""

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Account Configuration
        Parameters:
          - ToolsAccount
      - Label:
          default: Project Configuration
        Parameters:
          - ProjectIdentifier
          - ArtifactBuckets
          - KmsKeyArns
          - AdditonalRegions
      - Label:
          default: Misc
        Parameters:
          - PermissionsBoundary
    ParameterLabels:
      ToolsAccount:
        default: Tools Account
      ArtifactBuckets:
        default: Artifact Buckets
      KmsKeyArns:
        default: KMS Key ARNs
      AdditonalRegions:
        default: Additional Regions
      ProjectIdentifier:
        default: Project Identifier
      PermissionsBoundary:
        default: Permissions Boundary


Conditions:

  SecondRegionCondition: !Equals [ !Ref AdditonalRegions, 1 ]

  PermissionsBoundaryCondition: !Not [!Equals [!Ref PermissionsBoundary, ""]]

Resources:

  CrossAccountRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectIdentifier}-CrossAccountRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${ToolsAccount}:root
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkFullAccess
      Path: /

  CrossAccountPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${ProjectIdentifier}-CrossAccountPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:*
              - s3:*
              - codecommit:BatchGetRepositories
              - codecommit:Get*
              - codecommit:GitPull
              - codecommit:List*
              - codecommit:CancelUploadArchive
              - codecommit:UploadArchive
              - codecommit:GetRepositoryTriggers
              - codecommit:PutRepositoryTriggers
              - codecommit:TestRepositoryTriggers
            Resource: "*"
          - Action:
              - iam:PassRole
            Condition:
              StringEqualsIfExists:
                iam:PassedToService:
                  - !Sub cloudformation.${AWS::URLSuffix}
                  - !Sub elasticbeanstalk.${AWS::URLSuffix}
                  - !Sub ec2.${AWS::URLSuffix}
                  - !Sub ecs-tasks.${AWS::URLSuffix}
            Effect: Allow
            Resource: "*"
          - Effect: Allow
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource:
              - !Select [ 0, !Ref KmsKeyArns ]
              - !If
                - SecondRegionCondition
                - !Select [1, !Ref KmsKeyArns]
                - !Ref AWS::NoValue
      Roles:
        - !Ref CrossAccountRole

  CloudFormationDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectIdentifier}-CloudFormationDeployRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !Sub cloudformation.${AWS::URLSuffix}
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      PermissionsBoundary: !If [ PermissionsBoundaryCondition, !Ref PermissionsBoundary, !Ref "AWS::NoValue" ]

  CloudFormationDeployPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${ProjectIdentifier}-CloudFormationDeployPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:GetBucketPolicy
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:PutObject
            Resource:
              - !Join ["", ["arn:aws:s3:::", !Select [0, !Ref ArtifactBuckets], "/*"]]
              - !If
                - SecondRegionCondition
                - !Join ["", ["arn:aws:s3:::", !Select [1, !Ref ArtifactBuckets], "/*"]]
                - !Ref AWS::NoValue
          - Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - !Join ["", ["arn:aws:s3:::", !Select [0, !Ref ArtifactBuckets]]]
              - !If
                  - SecondRegionCondition
                  - !Join ["", ["arn:aws:s3:::", !Select [1, !Ref ArtifactBuckets]]]
                  - !Ref AWS::NoValue
          - Effect: Allow
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource:
              - !Select [ 0, !Ref KmsKeyArns ]
              - !If
                - SecondRegionCondition
                - !Select [1, !Ref KmsKeyArns]
                - !Ref AWS::NoValue
      Roles:
        - !Ref CloudFormationDeployRole

Outputs:
  StackName:
    Description: Name of the current stack
    Value: !Ref AWS::StackName

  CrossAccountRoleArn:
    Description: CodePipeline role Arn
    Value: !GetAtt CrossAccountRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}:CrossAccountRoleArn

  CloudFormationDeployRoleArn:
    Description: CloudFomration deploy role Arn
    Value: !GetAtt CloudFormationDeployRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}:CloudFormationDeployRoleArn
