version: '3.7'

services:
  pypi:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ../../src/todoapi/dist:/packages:ro
    networks:
      - pypi

networks:
  pypi:
    driver: bridge